export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const GET_FILTERED_USERTYPE = "GET_FILTERED_USERTYPE"
export const SET_ALERT = " SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_USERS = "GET_USERS";
export const EMAIL_SENT = "EMAIL_SENT";

export const ADD_RESULT = 'ADD_RESULT';
export const ERROR_RESULT = 'ERROR_RESULT';

export const CLEAR_FILTER = "CLEAR_FILTER";

export const GET_ERRORS = 'GET_ERRORS';
export const LOAD_QUIZ = 'LOAD_QUIZ';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_QUIZ_LOADING = 'SET_QUIZ_LOADING';
export const END_FREE_QUIZ = 'END_FREE_QUIZ';
export const CLEAR_QUIZ_STATS = 'CLEAR_QUIZ_STATS';
export const SET_USER_COLOR = 'SET_USER_COLOR';


export const GET_PROJECT = "GET_PROJECT";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const CLEAR_PROJECT = "CLEAR_PROJECT";
export const FILTER_PROJECT = "FILTER_PROJECT";

export const GET_INVESTMENT = "GET_INVESTMENT";
export const GET_USERS_INVESTMENTS = "GET_USERS_INVESTMENTS";
export const SET_CURRENT_INVESTMENT = "SET_CURRENT_INVESTMENT";
export const GET_INVESTMENTS = "GET_INVESTMENTS";
export const GET_CURRENCIES = "GET_CURRENCIES";
export const ADD_INVESTMENT = "ADD_INVESTMENT";
export const FETCH_INVESTMENT = "FETCH_INVESTMENT";
export const EDIT_INVESTMENT = "EDIT_INVESTMENT";
export const DELETE_INVESTMENT = "DELETE_INVESTMENT";
export const INVESTMENT_ERROR = "INVESTMENT_ERROR";
export const CLEAR_INVESTMENT = "CLEAR_INVESTMENT";
export const FILTER_INVESTMENT = "FILTER_INVESTMENT";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAILURE = "ADD_IMAGE_FAILURE";

export const GET_EXPENSE = "GET_EXPENSE";
export const SET_CURRENT_EXPENSE = "SET_CURRENT_EXPENSE";
export const GET_USERS_EXPENSES = "GET_USERS_EXPENSES";
export const GET_EXPENSES = "GET_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const FETCH_EXPENSE = "FETCH_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EXPENSE_ERROR = "EXPENSE_ERROR";
export const CLEAR_EXPENSE = "CLEAR_EXPENSE";
export const FILTER_EXPENSE = "FILTER_EXPENSE";

export const GET_CUSTOMER_PAY = "GET_CUSTOMER_PAY";
export const SET_CURRENT_CUSTOMER_PAY = "SET_CURRENT_CUSTOMER_PAY";
export const GET_CUSTOMER_PAYS = "GET_CUSTOMER_PAYS";
export const FETCH_CUSTOMERPAY = "FETCH_CUSTOMERPAY";


export const CUSTOMER_BASED_PAY = "CUSTOMER_BASED_PAY";
export const ADD_CUSTOMER_PAY = "ADD_CUSTOMER_PAY";
export const EDIT_CUSTOMER_PAY = "EDIT_CUSTOMER_PAY";
export const DELETE_CUSTOMER_PAY = "DELETE_CUSTOMER_PAY";
export const CUSTOMER_PAY_ERROR = "CUSTOMER_PAY_ERROR";
export const CLEAR_CUSTOMER_PAY = "CLEAR_CUSTOMER_PAY";
export const FILTER_CUSTOMER_PAY = "FILTER_CUSTOMER_PAY";


export const GET_CUSTOMER = "GET_CUSTOMER";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const FILTER_CUSTOMER = "FILTER_CUSTOMER";



export const GET_ESTIMATE = "GET_ESTIMATE";
export const SET_CURRENT_ESTIMATE = "SET_CURRENT_ESTIMATE";
export const GET_ESTIMATES = "GET_ESTIMATES";
export const ADD_ESTIMATE = "ADD_ESTIMATE";
export const EDIT_ESTIMATE = "EDIT_ESTIMATE";
export const DELETE_ESTIMATE = "DELETE_ESTIMATE";
export const ESTIMATE_ERROR = "ESTIMATE_ERROR";
export const CLEAR_ESTIMATE = "CLEAR_ESTIMATE";
export const FILTER_ESTIMATE = "FILTER_ESTIMATE";
// REPORTS

export const GET_ALL_CUSTOMER_PAYS = "GET_ALL_CUSTOMER_PAYS";
export const GET_ALL_EXPENSES = "GET_ALL_EXPENSES";
export const GET_ALL_INVESTMENTS = "GET_ALL_INVESTMENTS";
export const OVER_ALL_SUM_INV = "OVER_ALL_SUM_INV";
export const OVER_ALL_SUM_EXP = "OVER_ALL_SUM_EXP";
export const OVER_ALL_SUM_CUSTPAY = "OVER_ALL_SUM_CUSTPAY";

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_ALL_ESTIMATES = "GET_ALL_ESTIMATES";
export const GET_PROJECTWISE_INVESTMENTS = "GET_PROJECTWISE_INVESTMENTS";
export const GET_TOTALWISE_INVESTMENTS = "GET_TOTALWISE_INVESTMENTS";
export const GET_TOTALWISE_EXPENSES = "GET_TOTALWISE_EXPENSES";
export const GET_PROJECTWISE_EXPENSES = "GET_PROJECTWISE_EXPENSES";
export const GET_PROJECTWISE_CUSTPAY = "GET_PROJECTWISE_CUSTPAY";
export const GET_TOTALWISE_CUSTPAY = "GET_TOTALWISE_CUSTPAY";
export const GET_USERS_SUM_INVESTMENTS = "GET_USERS_SUM_INVESTMENTS";
export const GET_USERS_SUM_EXPENSES = "GET_USERS_SUM_EXPENSES";
export const CUST_SUM_PAYMENT = "CUST_SUM_PAYMENT";

export const GET_MONTHLY_INVESTMENTS = "GET_MONTHLY_INVESTMENTS";
export const GET_MONTHLY_EXPENSES = "GET_MONTHLY_EXPENSES";
export const GET_MONTHLY_CUSTPAY = "GET_MONTHLY_CUSTPAY";

export const GET_USER_MONTHLY_INVESTMENTS = "GET_USER_MONTHLY_INVESTMENTS";
export const GET_USER_MONTHLY_EXPENSES = "GET_USER_MONTHLY_EXPENSES";
export const GET_USER_MONTHLY_CUSTPAY = "GET_USER_MONTHLY_CUSTPAY";
